name: Release tagged revision

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Esatto.DataAccess
      run: dotnet pack Esatto.DataAccess -c Release -p:Version=${{github.ref_name}}
    - name: NugetPush Esatto.DataAccess
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json --api-key ${{secrets.MG_NUGET_SECRET}} Esatto.DataAccess/bin/Release/Esatto.DataAccess.${{github.ref_name}}.nupkg